Stabilize GHA (#2)
- Fix all the bugs that were present.
- Remove everything related to JS eco system, such as eslint, .nycrc.json, etc.
- Do proper renaming.
- Update README with the relevant information.
- Add support 8 types of OS.
- Add support of `props` data format.
- Add functional tests.
- Remove irrelevant pre-commit hooks.
- Update `action.yml`.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,155 +1,109 @@
 ---
-name: 'YAML/JSON/XML Converter Action'
+name: 'Data Format Converter Action'
 author: Yevhen Fabizhevskyi
-description: 'This action takes file that in YAML/JSON/XML format and produces it in output in YAML/JSON/XML format.'
+description: 'This action converts file with one format to another format, e.g. from JSON to XML, from YAML to JSON, etc.'
 branding:
   icon: copy
   color: green
 inputs:
-  path:
-    description: 'Path to the file'
+  input:
+    description: 'Path to the file with the data to be converted.'
     required: true
   from:
-    description: 'Format of a file. Possible values: json, xml, yaml.'
+    description: 'Format of a file. Possible values: json, xml, yaml, props.'
     required: true
   to:
-    description: 'Format of a file as a result. Possible values: json, xml, yaml.'
+    description: 'Format of a file as a result. Possible values: json, xml, yaml, props.'
     required: true
 outputs:
-  data:
-    description: 'Content of a file in a format that is defined in format_to argument.'
+  output:
+    description: 'Converted data.'
     value: ${{ steps.result.outputs.data }}
 runs:
   using: 'composite'
   steps:
-    - name: Check yq
-      id: check_yq
+    - name: Collect yq info
+      id: yq_info
+      env:
+        YQ_VERSION: v4.28.1
+        YQ_TEMP_FILE: .data-format-converter-action
       run: |
+        echo "YQ_VERSION=$YQ_VERSION" >> $GITHUB_OUTPUT
+        echo "YQ_TEMP_FILE=$YQ_TEMP_FILE" >> $GITHUB_OUTPUT
         result=$(if command -v yq >/dev/null 2>&1; then echo true; else echo false; fi)
-        echo "exists=$result" >> $GITHUB_OUTPUT
+        echo "YQ_INSTALLED=$result" >> $GITHUB_OUTPUT
+        if [[ "${{ runner.os }}" == "macOS" ]]; then
+          if [[ "${{ runner.arch }}" == "ARM64" ]]; then
+            YQ_BINARY=yq_darwin_arm64
+          else
+            YQ_BINARY=yq_darwin_amd64
+          fi
+        elif [[ "${{ runner.os }}" == "Windows" ]]; then
+          if [[ "${{ runner.arch }}" == "X86" ]]; then
+            YQ_BINARY=yq_windows_386.exe
+          else
+            YQ_BINARY=yq_windows_amd64.exe
+          fi
+        elif [[ "${{ runner.os }}" == "Linux" ]]; then
+          if [[ "${{ runner.arch }}" == "X86" ]]; then
+            YQ_BINARY=yq_linux_386
+          elif [[ "${{ runner.arch }}" == "ARM" ]]; then
+            YQ_BINARY=yq_linux_arm
+          elif [[ "${{ runner.arch }}" == "ARM64" ]]; then
+            YQ_BINARY=yq_linux_arm64
+          else
+            YQ_BINARY=yq_linux_amd64
+          fi
+        else
+          echo "::error file=action.yml,line=44,col=11,endColumn=11::${{ runner.os }} is not supported"
+          exit 1
+        fi
+        echo "YQ_BINARY=$YQ_BINARY" >> $GITHUB_OUTPUT
+        if [[ "${{ runner.os }}" == "Windows" ]]; then
+          echo "YQ_EXEC=yq.exe" >> $GITHUB_OUTPUT
+        else
+          echo "YQ_EXEC=yq" >> $GITHUB_OUTPUT
+        fi
       shell: bash
-    # Linux x86
-    - name: Install mikefarah/yq (Linux X86)
-      if: ${{ steps.check_yq.outputs.exists == false && inputs.from != 'xml' && runner.os == 'Linux' && runner.arch == 'X86' }}
+    - name: Check same from and to
+      if: ${{ inputs.from == inputs.to }}
+      run: cp "${{ inputs.input }}" "${{ steps.yq_info.outputs.YQ_TEMP_FILE }}"
+      shell: bash
+    - name: Install mikefarah/yq (Linux / macOS)
+      if: ${{ inputs.from != inputs.to && steps.yq_info.outputs.YQ_INSTALLED == 'false' && runner.os != 'Windows' }}
       env:
-        YQ_VERSION: v4.28.1
-        YQ_BINARY: yq_linux_386
+        YQ_URL: https://github.com/mikefarah/yq/releases/download/${{ steps.yq_info.outputs.YQ_VERSION }}/${{ steps.yq_info.outputs.YQ_BINARY }}
       run: |
-        wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY} -O .
-        chmod +x yq
-        echo "$(pwd)" >> $GITHUB_PATH
+        wget $YQ_URL -O .
+        mv ${{ steps.yq_info.outputs.YQ_BINARY }} ${{ steps.yq_info.outputs.YQ_EXEC }}
+        chmod +x ${{ steps.yq_info.outputs.YQ_EXEC }}
       shell: bash
-    # Linux AMD64
-    - name: Install mikefarah/yq (Linux AMD64)
-      if: ${{ steps.check_yq.outputs.exists == false && inputs.from != 'xml' && runner.os == 'Linux' && runner.arch == 'X64' }}
+    - name: Install mikefarah/yq (Windows)
+      if: ${{ inputs.from != inputs.to && steps.yq_info.outputs.YQ_INSTALLED == 'false' && runner.os == 'Windows' }}
       env:
-        YQ_VERSION: v4.28.1
-        YQ_BINARY: yq_linux_amd64
+        YQ_URL: https://github.com/mikefarah/yq/releases/download/${{ steps.yq_info.outputs.YQ_VERSION }}/${{ steps.yq_info.outputs.YQ_BINARY }}
+      run: Invoke-WebRequest -URI $Env:YQ_URL -OutFile ${{ steps.yq_info.outputs.YQ_EXEC }}
+      shell: pwsh
+    - name: Add mikefarah/yq to PATH
+      if: ${{ inputs.from != inputs.to && steps.yq_info.outputs.YQ_INSTALLED == 'false' }}
       run: |
-        wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY} -O .
-        chmod +x yq
         echo "$(pwd)" >> $GITHUB_PATH
+        echo "::debug::${{ steps.yq_info.outputs.YQ_BINARY }}@${{ steps.yq_info.outputs.YQ_VERSION }} has been installed"
       shell: bash
-    # Linux ARM
-    - name: Install mikefarah/yq (Linux ARM)
-      if: ${{ steps.check_yq.outputs.exists == false && inputs.from != 'xml' && runner.os == 'Linux' && runner.arch == 'ARM' }}
-      env:
-        YQ_VERSION: v4.28.1
-        YQ_BINARY: yq_linux_arm
-      run: |
-        wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY} -O .
-        chmod +x yq
-        echo "$(pwd)" >> $GITHUB_PATH
-      shell: bash
-    # Linux ARM64
-    - name: Install mikefarah/yq (Linux ARM64)
-      if: ${{ steps.check_yq.outputs.exists == false && inputs.from != 'xml' && runner.os == 'Linux' && runner.arch == 'ARM64' }}
-      env:
-        YQ_VERSION: v4.28.1
-        YQ_BINARY: yq_linux_arm64
-      run: |
-        wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY} -O .
-        chmod +x yq
-        echo "$(pwd)" >> $GITHUB_PATH
-      shell: bash
-    # macOS ARM64
-    - name: Install mikefarah/yq (macOS ARM64)
-      if: ${{ steps.check_yq.outputs.exists == false && inputs.from != 'xml' && runner.os == 'macOS' && runner.arch == 'ARM64' }}
-      env:
-        YQ_VERSION: v4.28.1
-        YQ_BINARY: yq_darwin_arm64
-      run: |
-        wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY} -O .
-        chmod +x yq
-        echo "$(pwd)" >> $GITHUB_PATH
-      shell: bash
-    # macOS AMD64
-    - name: Install mikefarah/yq (macOS AMD64)
-      if: ${{ steps.check_yq.outputs.exists == false && inputs.from != 'xml' && runner.os == 'macOS' && runner.arch == 'X64' }}
-      env:
-        YQ_VERSION: v4.28.1
-        YQ_BINARY: yq_darwin_amd64
-      run: |
-        wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY} -O .
-        chmod +x yq
-        echo "$(pwd)" >> $GITHUB_PATH
-      shell: bash
-    # Windows AMD64
-    - name: Install mikefarah/yq (Windows AMD64)
-      if: ${{ steps.check_yq.outputs.exists == false && inputs.from != 'xml' && runner.os == 'Windows' && runner.arch == 'X64' }}
-      env:
-        YQ_VERSION: v4.28.1
-        YQ_BINARY: yq_windows_amd64.exe
-      run: |
-        wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY} -O .
-        chmod +x yq
-        echo "$(pwd)" >> $GITHUB_PATH
-      shell: bash
-    # Windows x86
-    - name: Install mikefarah/yq (Windows X86)
-      if: ${{ steps.check_yq.outputs.exists == false && inputs.from != 'xml' && runner.os == 'Windows' && runner.arch == 'X86' }}
-      env:
-        YQ_VERSION: v4.28.1
-        YQ_BINARY: yq_windows_386.exe
-      run: |
-        wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY} -O .
-        chmod +x yq
-        echo "$(pwd)" >> $GITHUB_PATH
-      shell: bash
-    # From YAML/JSON
-    - name: JSON/YAML to JSON/XML/YAML
-      if: ${{ inputs.from != 'xml' }}
-      run: yq -P '${{ inputs.path }}' -o=${{ inputs.to }} > .yaml-json-xml-converter-action
+    - name: Convert
+      if: ${{ inputs.from != inputs.to }}
+      run: ${{ steps.yq_info.outputs.YQ_EXEC }} -P '${{ inputs.input }}' -p=${{ inputs.from }} -o=${{ inputs.to }} > '${{ steps.yq_info.outputs.YQ_TEMP_FILE }}'
       shell: bash
     - name: Uninstall mikefarah/yq
-      if: ${{ inputs.from != 'xml' }}
-      run: rm -f yq
-      shell: bash
-    # From XML
-    - name: Install kislyuk/yq
-      if: ${{ inputs.from == 'xml' }}
-      run: pip install yq==3.1.0
-      shell: bash
-    - name: XML to JSON
-      if: ${{ inputs.from == 'xml' && inputs.to == 'json' }}
-      run: xq . '${{ inputs.path }}' > .yaml-json-xml-converter-action
-      shell: bash
-    - name: XML to YAML
-      if: ${{ inputs.from == 'xml' && inputs.to == 'yaml' }}
-      run: xq . '${{ inputs.path }}' | yq -y . > .yaml-json-xml-converter-action
-      shell: bash
-    - name: Uninstall kislyuk/yq
-      if: ${{ inputs.from == 'xml' }}
-      run: pip uninstall -y yq
+      if: ${{ inputs.from != inputs.to && steps.yq_info.outputs.YQ_INSTALLED == 'false' }}
+      run: rm -f ${{ steps.yq_info.outputs.YQ_EXEC }}
       shell: bash
     # Output
     - name: Save output
       id: result
-      run: |
-        content=$(cat .yaml-json-xml-converter-action)
-        content="${content//'%'/'%25'}"
-        content="${content//$'\n'/'%0A'}"
-        content="${content//$'\r'/'%0D'}"
-        echo "data=$content" >> $GITHUB_OUTPUT
-        rm -f .yaml-json-xml-converter-action
-      shell: bash
+      uses: actions/github-script@v6
+      with:
+        script: |
+          const fs = require('fs');
+          core.setOutput('data', fs.readFileSync('${{ steps.yq_info.outputs.YQ_TEMP_FILE }}', 'utf-8').replace(/\s+$/gm, ''));
+          fs.unlinkSync('${{ steps.yq_info.outputs.YQ_TEMP_FILE }}');
